
export const dataFrom = [
    {
    id:1 ,
    imagen:"cataratasdeliguazu.jpg",
    destino:"Misiones",
    lugar:"Cataratas del Igúazu",
    estadia:" 4 dias y 3 noches.",
    hotel:"'Los Amigos' incluye desayuno y merienda, cuenta con cochera, piscina, vista a las amazonas, ademas de una suit con RotServis",
    stock: 50,
    excursiones:"Tendras la maravillosa experiencia de conocer una de las 7 maravillas del mundo, Las Cataratas del Igúazu, con tour por el parque nacional, lleno de selva y naturaleza",
    precio:"130.000$",
    categoryId: 2,
    descuento: true
    },
    {
    id:2 ,
    imagen:"ushuaia.jpg",
    destino:"Tierra del Fuego",
    lugar:"Ushuaia",
    estadia:" 5 dias y 4 noches.",
    hotel:"'Chaparros' este increible hotel cuenta con calefaccion en todas las habitaciones, desayuno incluido + restaurat gourmet dentro del hotel",
    stock: 50,
    excursiones:"Paseo con pinguinos en la isla Martillo y merienda en el mitador Bella Vista",
    precio:"150.000$",
    categoryId: 5,
    descuento: false
    },
    {
    id: 3 ,
    imagen:"jujuy7colores.jpg",
    destino:"Jujuy",
    lugar:"Purmamarca",
    estadia:" 3 dias y 2 noches.",
    hotel:"'Marianitos' cuenta con cena, terraza y piscina incluida + cochera",
    stock: 50,
    excursiones:"Tour por 'El cerro de los 7 colores'",
    precio:"100.000$",
    categoryId: 8,
    },
    {
    id: 4 ,
    imagen:"mendozaAconcagua.jpg",
    destino:"Mendoza",
    lugar:"Aconcagua",
    estadia:" 6 dias y 5 noches.",
    hotel:"'Oeste' este hotel cuenta con calefaccion en todas las habitaciones, routservis y desayuno incluido de 7am y 10:30am ",
    stock: 50,
    excursiones:"Paseo en bus por el parque provincial del Aconcagua, con hermosa vista a las montañas y una merienda incluida en el mirador que ahi mismo se encuentra ",
    precio:"115.000$",
    categoryId: 8,
    },
    {
    id: 5 ,
    imagen:"jujuy.jpg",
    destino:"Jujuy",
    lugar:"California",
    estadia:" 3 dias y 2 noches.",
    hotel:"Salinas Grandes",
    stock: 50,
    excursiones:"Visita al desierto de las salinas, este desierto posee cinco y diez millones de años cuando la cuenca se cubrió por completo de aguas provenientes de un volcán. ",
    precio:"100.000$",
    categoryId: 2,
    },
    {
    id: 6 ,
    imagen:"cordoba.jpg",
    destino:"Cordoba",
    lugar:"Villa Carlos Paz",
    estadia:" 5 dias y 4 noches.",
    hotel:"Luxom",
    stock: 50,
    excursiones:"Tour por el camino de las 100 curvas en bus, con comida incluida en el complejo 'Rowser'",
    precio:"80.000$",
    categoryId: 2,
    },
    {
    id: 7 ,
    imagen:"buenosAires.jpg",
    destino:"Buenos Aires",
    lugar:"Federal Capital",
    estadia:" 4 dias y 3 noches.",
    hotel:"9 de Julio",
    stock: 50,
    excursiones:"Tour por la hermosa ciudad de Buenos Aires, visitas nocturnas a los mejores Bares por al rededor de el hermoso Obelisco y tures matutinos opcionales para conocer maravillosos lugares como el teatro colon que ahi mismo se encuentra",
    precio:"60.000$",
    categoryId: 2,
    },
    {
    id: 8 ,
    imagen: "termas-entrerios.jpg",
    destino:"Entre Rios",
    lugar:"Federación",
    estadia:" 3 dias y 2 noches.",
    hotel:"Kanji-Home.spa",
    stock: 50,
    excursiones:"Completo 'Las Termas' cuenta con 4 incleibles piletas climatizadas, que permite su vicita ent odas las estaciones del año, ademas de que cuneta con un spa para relajarte, masajes y zauna",
    precio:"70.000$",
    categoryId: 8,
    },
    {
    id: 9 ,
    imagen:"peritomoreno.jpg",
    lugar:"Glaciar Perito Moreno",
    destino:"Santa Cruz",
    estadia:" 6 dias y 5 noches.",
    hotel:"Kilton",
    stock: 50,
    excursiones:"Tour por el impresionante glaciar de Perito Moreno, disfruta de esta hermosa vista mas la compañia de los lobos marinos que se acercan al parque nacional",
    precio:"160.000$",
    categoryId: 5,
    },
    {
    id: 10 ,
    imagen:"bariloche2.jpg",
    lugar:"Rio Negro",
    destino:"Bariloche",
    estadia:" 6 dias y 5 noches.",
    hotel:"RocaMar",
    stock: 50,
    excursiones:"Circuito chico, un completo de diversion donde bajas por un tobogan con una tabla de madera con regulación de velocidad, más merienda en el mismo completo en lo alto del lugar con vista a las maravillosas montañas y rio Nahuel Guapi ",
    precio:"120.000$",
    categoryId: 5,
    },
];


export default dataFrom;
